apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-telegram
    namespace: observability
type: Opaque
stringData:
    #ENC[AES256_GCM,data:eFMucufhZa7eRk+QSxVuXtqPpA3N1/4TWaQxyBcQCMBn4qNzHX+k1pSL,iv:lW5pzE14MZSC42p+xqdhO7kFv19LfmYNVE54V1ChQp0=,tag:9E+OnMwADux8HfrKosdZBQ==,type:comment]
    bot-token: ENC[AES256_GCM,data:XWmz3eUi596wEHo2Sk3FX9n76xX2RgLMgxldUAaj6eN01zRSMS+xJNVOgZI63w==,iv:FBlNsPZCZFcSac7n1YE9ENLoPNHBHAolkODpYiDEQAs=,tag:X/Nuld8MJ5nBZLBpUzajJw==,type:str]
sops:
    age:
        - recipient: age1g6uhy72aszly2j77d0wmy4mwy5f9ezxe2w9fu2ensal4mn5uufyqqpcf8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQVIyUnRTRlgwakZiQTEy
            bTI2eU9sT2JsUWw3VlhrR21VNDVCK2lNbzJNCmhPQnFNckhKQk1wTFdxTG5KOHNM
            cHBPZStWUklJWk54VDdDZm1md2J0MEkKLS0tIGNQZTN5UjI2aGh0TnVESWYzd2Rv
            R3FzWHlzUmlMOS84Z1hzQ25CTXo1V0EKXFYzLR6MS/id0HbQxYraRMxQPXUsjyj5
            Pn+6jgu4Oo8WAkJOHFKeyldhKWw3s1+o9lcWJQY70KlXimvthcVJlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T13:24:12Z"
    mac: ENC[AES256_GCM,data:RHEiAqAzKKRaxO3Lgqw4yxjC2V/kmwuc5FlCAL27Sgb52szMgocdkEs5lUMw8/3SkcHoT36CauNw+vN/uGMD1h5meqAHc2MYyp2xx9eDTTgqsbvrp3gb4Ry2lJnoz1sl3zKBts383yiPnaqsimgdrz5AULwI57MXWwdx4Uh/fnE=,iv:2itvsr8MGD91cA4ScwbsBiXDiQNv48i7BwAj09CVq8M=,tag:LeDq+2XqVRIEcc1zFCCFyA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
