# Grafana admin credentials
# This file should be encrypted with SOPS before committing
# Run: sops --encrypt --in-place grafana-secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: observability
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:X0/y5hg=,iv:z5/bt7fdwTCug6878ZO1MSqeScGtH+4IqwimPoQaOO8=,tag:ghi8Dyzqhw4SvURhcD9sRA==,type:str]
    #ENC[AES256_GCM,data:V4/wuJ81JjeKGp/9LcxeZxJBpDlxgDXZA6k=,iv:lHgvLzMbrLszkJn9nFYaqakhzqyERJw0hsoY+hmdQQY=,tag:t9aniwweFFWT2Dt+34r6ew==,type:comment]
    admin-password: ENC[AES256_GCM,data:F4rVcHaTFwUv5pOoFFD8l49N9+yRYDqca8JupICOJq8=,iv:fQrifoTiLBO8PQryc6bB4gbXHk8ZaRMMgcvHGlVlUA8=,tag:iXwJCLSv5NriwzeVMC0DWQ==,type:str]
    oauth-client-secret: ENC[AES256_GCM,data:/GsCiMPeOapbuEPv6mmvF8dzNeXVGai8j4Ih38aNhTtKEPpxWKPcz7TpenbMPYbuN1+mvnRyUN9FrjSaPR6gkA==,iv:4MoSOpjRS9Ic/h8uqAICtoYtib5iVRu2h9jRj4niIuI=,tag:14vDkKjAnpruE4RlivNSAg==,type:str]
sops:
    age:
        - recipient: age1g6uhy72aszly2j77d0wmy4mwy5f9ezxe2w9fu2ensal4mn5uufyqqpcf8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1OEJHVmdKVzlhTGtqUHhP
            MWIxUlM0T0VOT1ZLeGpCdDVlM1QxTGpucVJnCmoxTFc1NGQzNkhzTEdMQ21TTFI3
            WlZWenJjSEsxL096WnJEdnpsZThiNEkKLS0tIElCSzBWMnowc1A3ZytNMGcyaHo2
            dXVERmdkMVhnUVhkZjhTY1AzREl4c1UKxivG2iwHyAy8MSnVblcUvdlO1TqMSch7
            wy1lftgQWjBmHvlHg/mfDONC7yjHdITThQwod99ZDy54jO0r9npxmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T07:18:56Z"
    mac: ENC[AES256_GCM,data:KuNCmlwuE39gCpExLJMhF5Iau4ZErtNVXPw1NVE1z3M4Gu7SgDPBHShOSKWMdtWkck72W8SjM5Nj4NojgnXuea/QDh10VV5CD6f4IQXhpNKLE04SRoc/fdNZoPlZhyzuxkp/hRKbuiFLcf/QXqSPGyYVN3ikD6QV+WOviLEiVn0=,iv:TKDp70XAntFoscij8OAi+TGA+88upvZHV5qXG4Vs9ZU=,tag:qwFDkIhLudy+xMVNyy+20w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
