# Homepage secrets - API keys for widgets
#
# IMPORTANT: Fill in the values below, then encrypt with SOPS:
#   sops --encrypt --in-place secrets.sops.yaml
#
# Where to find API keys:
#   - Sonarr/Radarr/Prowlarr: Settings > General > API Key
#   - Overseerr: Settings > General > API Key
#   - Plex: Get token from https://www.plexopedia.com/plex-media-server/general/plex-token/
#   - qBittorrent: Username/password from WebUI settings
#
apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: media
type: Opaque
stringData:
    #ENC[AES256_GCM,data:xJP/Pk6WyKv3oNNYfoOW+oQY,iv:/3XcIzm2xiFYQj052vCRcXn0Jo6EnErV32GiXDJK9XA=,tag:ZvgbtJ1L63Rc/H0Ib4Jcxg==,type:comment]
    HOMEPAGE_VAR_SONARR_API_KEY: ENC[AES256_GCM,data:dOh3Ul1cr8t711lW3rnF+Zuv7MfKE3CKpNYhItCm/pY=,iv:zPmc6t+yS81zGspxwOF52RCil6tlmYRSkgtRWo4YITE=,tag:J6X90mBHuSQWm4PkhhdnAg==,type:str]
    HOMEPAGE_VAR_RADARR_API_KEY: ENC[AES256_GCM,data:ZXdRUZc2sM7Cv/YeFJfIcoQRXDmHtSYj2Ji+7luwvlw=,iv:Dfqzhsees2LjHrYMQhm65o+i2LOYVS+qqRh14NMxOYU=,tag:kkAaARHtt3JYFPix1rbSJA==,type:str]
    HOMEPAGE_VAR_PROWLARR_API_KEY: ENC[AES256_GCM,data:NQy3HCJZSQZaHDW23Rrzz6hyDs+9rncCkNX0ysf52gY=,iv:Z4tugAdh/xdDjcC5bE3CfaN7OaSSQUHIxLNFXqYvlyE=,tag:ytiG3TJQJ2YOq5fkAsOQmg==,type:str]
    HOMEPAGE_VAR_OVERSEERR_API_KEY: ENC[AES256_GCM,data:bQfu9RFreDxmjvn/4oi3O9tT/V8ZLmiIItFNmyCzjC1OjPlf903fsTS4hvJyEicOK4Ml8wi+wWms46Uc/My+09pjOhE=,iv:Rf2amwZUrP6/PprUrSVztNbsgRcqMJ7c/BEr8N9QWwE=,tag:ZDA6rvEot4kDKjlj3pYIdA==,type:str]
    #ENC[AES256_GCM,data:0aSq2dJ/u68C2PI=,iv:/+qZZ9SeQeWaLCQbtx/EKntt/cGu1K7toCLJB5gkIKE=,tag:+m9clFKQl/lElLec830NUw==,type:comment]
    HOMEPAGE_VAR_PLEX_TOKEN: ENC[AES256_GCM,data:rqH4FkFPOHrJ1PEtbiR0vGGjkfg=,iv:IqvAz69C4mJ2T362snUyhHtkb48FQeDDmw9gZwMrXsE=,tag:Jr+cxS6Ilr7sapcSANEABg==,type:str]
    #ENC[AES256_GCM,data:cUaPkR1wSkUcg+z1EYwgaG2Dz95yzOD0,iv:KHc2Vnsq9IE8exCkPquwQ3eflh7jzC3PfAhl5JOUeIc=,tag:JjxmlnkuIrTknqDmxU25dA==,type:comment]
    HOMEPAGE_VAR_QBITTORRENT_USERNAME: ENC[AES256_GCM,data:LqSyY9w=,iv:sa4Epg8e68mpC4DPQUhyWv354YpK5ZR/+YazRcPIlUs=,tag:3QbGKrOfYHcZ3FrWQrG8Fg==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:10hEieOi,iv:WtqAX3b8ZYuXMUWOrMxpLJh0OlX1bIKUz/RRQLudcrI=,tag:E1j3lwmhZMbIZLuEFKySKA==,type:str]
sops:
    age:
        - recipient: age1g6uhy72aszly2j77d0wmy4mwy5f9ezxe2w9fu2ensal4mn5uufyqqpcf8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2N0VRUUsxVjllNU5rekh1
            OWpCelhYMDBWMFo2TTJaenc2WU9DT25UejNJCkxQQ1ZHazFGR3VSSnlPZWh6NXV4
            TVNPT2RQQnlJZFhwNHE1V0hLWTNoajAKLS0tIHpTb0ZnN0drYXdDWTdEWUt6RE0w
            VUdmdEpvWVl5bEFrR2JHMXB0YW9YbGsKHgOZnyYL7OaHyc/U3cGaLkhtr3uuGbbD
            74f3ZvsoPFNnJ0Va0cZK55faq0t9buao6TsMvjk7J7XE74z7JPlV6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T08:06:17Z"
    mac: ENC[AES256_GCM,data:wLkR3wIR+RFe6jF2Kq1GFEldfpd6NObfht44AKs9ce/lFiUna4egwvFabq+WtxW0d+Ab0zml3vwTS3IXzL3O/NdUh6JS6Pq3q3OGwYF8bDS1cHfBB31lnaI/3s2Pt8omBmh44B9onMET5xaXGHtzFx4I9LzDV/vjjfyS6X6igJw=,iv:NhnUW86Rt7ypP08PJhNsJYHDDrsN8UelwbYOsWZzRIg=,tag:56eAnfCGaFwD32zUA36AYg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
