apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://cloudflare.github.io/helm-charts
    chart: cloudflare-tunnel
    targetRevision: 0.3.2
    helm:
      valuesObject:
        # Cloudflare Tunnel configuration
        cloudflare:
          # Tunnel ID - required for cloudflared to know which tunnel to run
          # Note: tunnelName is used by the chart to set the 'tunnel' config value
          tunnelName: f725ee00-7559-4fa2-ad97-cf4044b3770b
          
          # Tunnel credentials from SOPS-encrypted secret
          secretName: cloudflared-credentials
          
          # Ingress rules - route traffic to services
          # Note: The chart automatically adds a catch-all http_status:404 rule
          ingress:
            # Plex - public access
            - hostname: plex.lorenzodebie.be
              service: http://plex.media.svc.cluster.local:32400
            
            # Overseerr - public access for media requests
            - hostname: requests.lorenzodebie.be
              service: http://overseerr.media.svc.cluster.local:5055

            # Wordpress - Wedding RSVP Site
            - hostname: wedding.lorenzodebie.be
              service: http://wp-wedding.wedding.svc.cluster.local:80
        
        replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
