# Cloudflare Tunnel credentials
# This file should be encrypted with SOPS before committing
# 
# To create a tunnel:
# 1. Install cloudflared: brew install cloudflared
# 2. Login: cloudflared tunnel login
# 3. Create tunnel: cloudflared tunnel create homelab
# 4. Get credentials from ~/.cloudflared/<tunnel-id>.json
# 5. Copy the values below and encrypt with SOPS
#
# Run: sops --encrypt --in-place credentials.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: cloudflared
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Q1f31uH+F4ZVlnMC1OV0J6JyYLKN/4JrJmUuhOZj8QBbLS0Mw2E=,iv:qFiK94fvHGiovz7jgSaHlWB5iMojgyd21oXQ9zd4nG8=,tag:iaZsZwovUeQJR7napzMxTg==,type:comment]
    TunnelID: ENC[AES256_GCM,data:Q5caQnan2Mjq4NE/76lexD3vVw2GUHCrGg8iyFGghFGA4+Lq,iv:nzVhvLqR/9nYPRc21DWC6Q+D75RYKzO6xkDF7ChqamM=,tag:ZBdirqkGTj0UNe+LMWyLQA==,type:str]
    AccountTag: ENC[AES256_GCM,data:bMoXjoa8SH+ohaoL24/+A3sEIjRAmJ9iRGqs/e6NgjQ=,iv:dWEP7bNlrU59s/iGZF8LefpDf6dT3GECVQNV6lay7Mo=,tag:wqMaRtWfthyzykevoPSnEQ==,type:str]
    TunnelSecret: ENC[AES256_GCM,data:uqSjdfYjAzj5vD/8d0O7H7S16UZez0leW5qxeoZcPGGKV+pRrwd9Rjnj3PU=,iv:DPg2gkLkA0Z1MqUeIrVg3chnIPxXWj3OkLCeOxxcrQE=,tag:vzb42h0AyKp1UI+oCfXgkA==,type:str]
sops:
    age:
        - recipient: age1g6uhy72aszly2j77d0wmy4mwy5f9ezxe2w9fu2ensal4mn5uufyqqpcf8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbFFMTkJsaGovU2x0cEZB
            NER6ZkcyVjA0QzhrVjdEcFg2c1Z1d1JFaUVJCkRLbEQzVTdjVmYrRjliVGJnVEdy
            UlpGdnJydzhhM3g4a2xCQUtBN21SOHcKLS0tIHBBSm5ES2ZXTkVWYkNUb0MrMDhC
            TTlHS01aVitwcnVmZitMalVndHlyREkKWL7MGxbSyitkujBGkchLyRpyp+4xKRIF
            ZRGEzU8P6yizr3yjC2mZizM3Yq0OLFAwtsGUAgQTDRCYWoC7SgDoKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T15:40:28Z"
    mac: ENC[AES256_GCM,data:8zTxkwLudXeuUo1KcCbossHAb/XwobCgaKdCJ0wL3KVuvWubGY3AYEfwADqckL4CSnnNnxuF7rmSJcXMLi9PL+hlDqade0vVHJL2vG1wl7pQzyCTkbWQ3F8NbRRGS0I4LdEMPjFqTNAh1Zs24YiGMIOZRdcCYdcbO/yjGPn/An4=,iv:V9KHHynBUimZaiIC+ebRHSNcI/Rco+McnfX2ftTRuaE=,tag:K0D78EqeRdlIsY+sY/jx/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
