# Cloudflare Tunnel credentials
# This file should be encrypted with SOPS before committing
# 
# To create a tunnel:
# 1. Install cloudflared: brew install cloudflared
# 2. Login: cloudflared tunnel login
# 3. Create tunnel: cloudflared tunnel create homelab
# 4. Get credentials from ~/.cloudflared/<tunnel-id>.json
# 5. Copy the values below and encrypt with SOPS
#
# Run: sops --encrypt --in-place credentials.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: cloudflared
type: Opaque
stringData:
    #ENC[AES256_GCM,data:b4RN7a5OOWXZNsW9ZCHgG3z35YauuAsKqJ8ig/WsYlKoLZQuaZBP4R+lASVwefBoN/u6DQkjet+YcnCwgJnaqJSpbd7vmEn8SQ/KbA==,iv:fMr2v6Qj53Q2OaOBpZgczQe/R1EmLYCHXqzK4ZREE+U=,tag:qWZHSTm/0mce3J7jFQsSlQ==,type:comment]
    credentials.json: ENC[AES256_GCM,data:kKdIvSuhBTCIxc3W6lBF4+tvAiKMeGvqsUXisnUXrZdj10Iyzb7rtfSLd095aPKhPVm24yHi4FAS336aea3fFKxdx9wASMkAc2OS1F0PG9GvI+Tf/AIFPPQ/HIorDVH88IyZN1BXE2vkurcTzfU71V9CyJGIgerH1n/jYSgK8U6PN9Kc0sQw9y09Eco2S86gBil+DiXaPV38VHdYnqZoQAiE,iv:E5mfE4SvwJRVhOuXnD4ck09bSHhLmO9I6PCeTroRXGw=,tag:JKftGbL82ZkR3FJbhVuXWw==,type:str]
sops:
    age:
        - recipient: age1g6uhy72aszly2j77d0wmy4mwy5f9ezxe2w9fu2ensal4mn5uufyqqpcf8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRTcyOG1xYTZPMFIxRExm
            NWppQ2FpUHZleWpWQzVKaDVaRDFwVTRiWHpZCnoyd01NdmFYdXlOWjN6K29zRGZL
            cS9BUU5oR204NmlwUFk3czhKNitkZjgKLS0tIG9SeTg3M3ZQTnhTYmhZa2taU1B6
            Z3lGWlRwWlVIaFhvQURQTFpNYjVBQmsKBRsPow89OZWX4IBnWLUf638q5zHv9I5C
            Mr2weTyXKLVg2M5740lZ0tLrbGj/0AnejQAn4unYP1cImgWTdtd4Rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T20:02:59Z"
    mac: ENC[AES256_GCM,data:WuQCfO3vcvuzRkNnXvevYVDHiyn1DPmG4XQb4he7poCgLcU30Vh0L9pVaOpa3YViKL5EmzygjKz9wvx6SjofNSNVkid+OfJAIAflTOOfUK5xva19PClcQ7iejIJK0UPVJzpcuH2M+TJmeCNL5iJV6osOF/IjeUdCyTEdjseXyM0=,iv:T3Msp9tmX0qEWWu69Ze7SmhE3LLXj3qOb0rkG2i2MrM=,tag:N2lLH3O/TvzW3RV+GBG+qg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
