apiVersion: v2
name: cilium-umbrella
description: Cilium CNI with L2 announcements and LB-IPAM configuration
type: application
version: 1.0.0
appVersion: "1.18.6"

dependencies:
  - name: cilium
    version: 1.19.1
    repository: https://helm.cilium.io
