# Tailscale OAuth credentials
# This file should be encrypted with SOPS before committing
#
# To create OAuth credentials:
# 1. Sign up at https://tailscale.com
# 2. Go to Settings > OAuth clients
# 3. Create a new OAuth client with these scopes:
#    - devices:read
#    - devices:write
#    - routes:read
#    - routes:write
# 4. Copy the client ID and secret below
#
# Run: sops --encrypt --in-place oauth-secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:rRphTsRDLrW+dMCybn/YJPc=,iv:5vmWPci4CSNRbwwTvBStyIOqt2o7CGQUSwvM0KGMYIU=,tag:mcfj4X6TMjpmLnms1/Fa5g==,type:str]
    client_secret: ENC[AES256_GCM,data:NXmTciiKWDyzX9b/j1jBCX3TDXxspRNlmz9/EmerCgBCJ3zD/fcEXqoq0V2rwmcmVQJfW/iOjJX/wi0cErXSQg==,iv:InThVVVvFaPJ7hQ9ASPcKl6bbjEOeujq4Ylqv8JbzBw=,tag:HT8RWB2hX52NIMaMB3639A==,type:str]
sops:
    age:
        - recipient: age1g6uhy72aszly2j77d0wmy4mwy5f9ezxe2w9fu2ensal4mn5uufyqqpcf8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTXhWMURIcElGNHVMclZI
            MmZRU3pTRzRhc1NNblo5c3JrVlRoc05zZEdVCmsyL05BblpWbW56YTRybUpmMHN1
            dFhBRXAvdVZ6bjZVR0o4TWdTQWxyYkkKLS0tIHEyV3hsSEhhTHBJY25adnZ5R0FS
            K1VtUGhHRlNUOFAxLy9NdW5pUzBVVEEKDxSI7QOUXkafAGW3YWMdYQHgMmcPjdty
            w/iK6pOoapgj+dBLIJdEhMy5Zz4FynKM5SjzFOCkzsGiFC+6caV84Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T15:40:35Z"
    mac: ENC[AES256_GCM,data:YnAWBUkq3m2GFvodDjTN2lWYwc8IAsZ7nqDvx+GEMl/bdLovAQdd9I40CfDZS0ZbxgDnvBoU+VSpZCVFbLBkTfiPUxpqwpyAGbE+aTDFxTVL1u3ce1FZ8Y0dJg+AirWhzCZlcXvKQY8zV318JDby1m4XDLHDlLPsj2mvriqVNU0=,iv:nHi5Yp7U4FihlDufhEj/9LkzT876Dm9h/X2wVSOA0WE=,tag:PXO0UzDkQsQu+OVQZYLayw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
