apiVersion: v2
name: nvidia-device-plugin
description: NVIDIA device plugin for Kubernetes
type: application
version: 1.0.0
appVersion: "0.18.2"

dependencies:
  - name: nvidia-device-plugin
    version: 0.18.2
    repository: https://nvidia.github.io/k8s-device-plugin
