nvidia-device-plugin:
  runtimeClassName: nvidia
  compatWithCPUManager: true
  nodeSelector:
    nvidia.com/gpu.present: "true"
  extraVolumes:
    - name: nvidia-driver-root
      hostPath:
        path: /usr/local/glibc
        type: Directory
  extraVolumeMounts:
    - name: nvidia-driver-root
      mountPath: /driver-root
      readOnly: true
  daemonset:
    extraVolumes:
      - name: nvidia-driver-root
        hostPath:
          path: /usr/local/glibc
          type: Directory
    extraVolumeMounts:
      - name: nvidia-driver-root
        mountPath: /driver-root
        readOnly: true
  config:
    default: default
    map:
      default: |-
        version: v1
        flags:
          migStrategy: none
          failOnInitError: true
          nvidiaDriverRoot: /driver-root
          nvidiaDevRoot: /
          plugin:
            passDeviceSpecs: true
            deviceListStrategy:
              - volume-mounts
