# Cloudflare API Token for DNS01 challenge
# This file should be encrypted with SOPS before committing
# Run: sops --encrypt --in-place cloudflare-secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:L7UXmUahlSkzzWB5UyLa4VCS4vFq3UCMAuyljIH+QfXN9WUUrcNfvg==,iv:G5HacVO1PSmnHnTPewI0rf+kVknKitLGr2xR83xGrNg=,tag:+BwCdSxcQJejEzPCes4mKw==,type:str]
sops:
    age:
        - recipient: age1g6uhy72aszly2j77d0wmy4mwy5f9ezxe2w9fu2ensal4mn5uufyqqpcf8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFeEVSWjI3SkpnZ2dXbVFa
            L1FUU1lpUTd0TzFMS3VOODJmNEpwOXdVS2x3CmhjcmNoWEI2clMwTFI0c0FmclpT
            NXRzb2hROTZHc1RxQ1pveWUxVnAwdncKLS0tIEJSYTBadWVvVDZlVmZabU5EcVZB
            eitza043RS9MaFRhSSsvSEtKYUZuc2MKKiGysGLwBBrEgRJv2NXkhDQhe3ASCSHM
            b0tVvgtlgIlSmjqsmP0R0mlYWGZgx/ypwxQh2wcv8qEpy0koyRTD/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T15:40:24Z"
    mac: ENC[AES256_GCM,data:KGlOMcEyT4aXUWw2Z8rumeZq5ZKzVITl+o19a0mPJnvr0UprsDAyJ4FzYor9OncHLwyMtwnpN6fAwDGhM5xyrasGtP7pBto+rqtzR8KfZ6jHl5zmIfNhwkj7w/68LMITHkLk2dfBehq2iLVX6buFLzuXtYNSPefKLCdRUnGU6uc=,iv:2M2E4NfbwSsoQWTwoPrP73Brbr+FwZ7hGLOMlBgAhW8=,tag:Bls0z4y/pTM3WEdV5cIvsA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
