# Authentik secrets
# This file should be encrypted with SOPS before committing
#
# Generate a secret key with: openssl rand -hex 32
# Generate a password with: openssl rand -base64 24
#
# Run: sops --encrypt --in-place secrets.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:BjYTrjP3vHAXRCbEDBB3MBrN/pb9D8QqNXMKnnpD5Jt/dnJwgbi4L6lhkcXfrkHUaMzZECO5U9tRdEVpm5N5cQ==,iv:Wa4clBiQJu/+EU+L8aeLPJHEvxlkEPn/MLiKXsrYQbA=,tag:lZev3IwxmgfhhTxvheqc9A==,type:str]
    postgresql-password: ENC[AES256_GCM,data:2wifHAXKJ3pV0mGY+/YxF6oNao+nMAW84pmZYJLUkUM=,iv:IxmxFjYFGHdFaKW4lXCg2YpPHSEO0Oe2DhLGd8dYP30=,tag:fnLQKto71iYyHIuQmN3/Ag==,type:str]
    #ENC[AES256_GCM,data:/u9+tBiAF9riKNJEs+wTbBcx5jJvcZo=,iv:HJO5OwPNJyBedUfGJCtnC9Ggnoyx5lW6eacIjgUdOpU=,tag:h0zyOdS8weFWhVW8ntFNZQ==,type:comment]
    bootstrap-password: ENC[AES256_GCM,data:x2gAESvpJiATWp8w1iXM4jQApaeD6PDqKXZ24XqLUGU=,iv:VX6pviNbzWz2iwfN4CtgxqB02C5Ppsyx3WYNjejCxG8=,tag:+Ouan/d0gnaOaK7oNCRSCA==,type:str]
    #ENC[AES256_GCM,data:NtLPPKp0KphOR3iXqoik9nnCn94=,iv:d4k+k7TEmdDHk8NxS4rO0Jb49HJhEM9nChX7dHuk6yo=,tag:tAR8h8B53K8ruNKpvUP1Uw==,type:comment]
    bootstrap-email: ENC[AES256_GCM,data:V+6N1+d7W9M8/YPSKmpKNUdmFRC57ho=,iv:TYrFWSaY1WKblqYJ4XXwdiLgcAOG6pvVcafL3iGusyQ=,tag:xFONzoxuHFI1Wbk7IZVYBA==,type:str]
    redis-password: ENC[AES256_GCM,data:z/2oIjD5TeNPsbsWoDScJ+4AvFKjGnQYJtgmRxXm7vU=,iv:k82sXSHofsAugIcFUdcUWyNJ3Z6ccq/ZV2+dlfLmW24=,tag:warv1yzqExRLN6CdwAuhNA==,type:str]
    #ENC[AES256_GCM,data:iFHYnSVC5t9BjSYhQtkciuUEbhOMbsqLhSMeeZOK7V3ZeOaJaxJjj1zlCyWlzeJha64upZbwtCpWpVrBj+cYMtS5znFumUka4ia0i+/WWek=,iv:u1PjxDzHCmAkRbTto5o/88z7EEIFD/HKqvQQKPmoVyQ=,tag:AiL83hyS3L+jLMvFQOQO4Q==,type:comment]
    argocd-oidc-client-secret: ENC[AES256_GCM,data:rECycsXDajRFvcy2qDs/pn57qp6wVT0odDBnlitSlX6XFb5TxVQ8A54sEp8=,iv:OdCNtwjxuCGHs4X+4a0Jyh4h7P2Lk5tsC9HFTLJ8wDY=,tag:dP813zmL31z5EAFuO9rlqA==,type:str]
    grafana-oidc-client-secret: ENC[AES256_GCM,data:futb7+HMFT5GaDh7ZQ//MruqjpiYNiiOzSquOu4Lv/f+5tfX70XOUl9bN8/CCUfQ9s8+MUDLKxOu5V6FAX4q8g==,iv:RwDGTwjqXhdWDu1NhfZ1W3Yx65gKHP7lL+6lFTes8/s=,tag:7xpt1tUbHCXu8bjFQvkkhg==,type:str]
sops:
    age:
        - recipient: age1g6uhy72aszly2j77d0wmy4mwy5f9ezxe2w9fu2ensal4mn5uufyqqpcf8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuaEZSMFVGenk2RzdmYk9T
            WUs0eThDdTVibzZQZDRneXlMRWVnNHR1RENBCktVMjlKQ05NWkdyR3FuZ0g4VDMy
            K3YwOW4rQmFkanRsWUtZVG4rdk43L1UKLS0tIGI3RDUzTGN0SGlIRHVQa1pTejZ5
            eHI5VkJXUUV1dEdteVJKQWlMWTBRdUkKVoPXkR3lUsS+Dw+bSUvoM2pHfLMFIeOh
            6Ol4eu2fyODgPNI0Ai9VqNaHP5GGmyIzzXzWPaqF4y+aWtvL7H3kHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T07:17:57Z"
    mac: ENC[AES256_GCM,data:207B1hMC3QDQdTUmBoR2NF7GTJE9IsdoeYP2X5g2lKobHb1t4tcFejyb00oGP3lZ+Pu9ocy2FEabxh9z2wEqjmeW36zpErTWTXREkbF125fgBddcTg2rcRLE371B4Rwj76O+EsvfR86OK76nw++PKnXLanf7apCCqT5virgujtM=,iv:FsyDVpEUmc4nP1ZzQshK14hNChAiXSRav7Nr7WNQDOo=,tag:1eo9uxmbv6PSQzztcceAiQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
